name: manage-azure-policy-ced18a76
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Configure_Advanced_Threat_Protection_to_be_enabled_on_open-source_relational_databases_e77fc0b3-f7e9-4c58-bc13-cb753ed8e46e/**'
#      - .github/workflows/manage-azure-policy-ced18a76.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ced18a76}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Configure_Advanced_Threat_Protection_to_be_enabled_on_open-source_relational_databases_e77fc0b3-f7e9-4c58-bc13-cb753ed8e46e/**
